; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = blackpill_f401cc

[env:blackpill_f401cc]
platform = ststm32 @ 19.7.1
board = blackpill_f401cc
framework = stm32cube
debug_tool = stlink
;upload_protocol = dfu
;build_type = release
lib_deps =
  # RECOMMENDED
  # Accept new functionality in a backwards compatible manner and patches
  lvgl/lvgl @ 9.5.0

build_flags =
    -D LV_CONF_INCLUDE_SIMPLE
    -I src
    -Os
    -ffunction-sections
    -fdata-sections
    ;-DHSE_VALUE=25000000

[env:blackpill_f411ce]
platform = ststm32 @ 19.7.1
board = blackpill_f411ce
framework = stm32cube
debug_tool = stlink
;upload_protocol = dfu
;build_type = release
lib_deps =
  # RECOMMENDED
  # Accept new functionality in a backwards compatible manner and patches
  lvgl/lvgl @ 9.5.0

build_flags =
    -D LV_CONF_INCLUDE_SIMPLE
    -I src
    -Os
    -ffunction-sections
    -fdata-sections
